/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("jacoco")
    id("org.sonarqube") version "4.4.1.3373"
}

jacoco {
    toolVersion = "0.8.7"
}

sonarqube {
    properties {
        // SonarQube server URL
        property("sonar.host.url", "http://192.168.1.15:9000")
        // SonarQube project key
        property("sonar.projectKey", "sonartest")
        // SonarQube project name
        property("sonar.projectName", "sonartest")
        // Other SonarQube properties as needed
        property("sonar.token", "squ_9c3d5a894320f76d82a731d2998f9145cd5bb77d")
        property("sonar.plugins.downloadOnlyRequired", "true")
    }
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    testImplementation(libs.junit.junit)
}

group = "helloworld"
version = "1.0-SNAPSHOT"
description = "Hello world sample web app"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
